version: '3'

services:
  app:
    image: mayankag96/springboot-docker:17
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - 3306:3306