name: SpringScale Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # - name: Setup Java JDK
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'oracle'
      #     java-version: '20'
      #     cache: maven
      #     check-latest: true
      - name: Setup java JDK 20
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 20

      - name: Build with Maven
        run: mvn clean install
