name: SpringScale Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: maven
          check-latest: true

      - name: Clean Install with Maven
        run: mvn clean install

      - name: Package with Maven
        run: mvn clean package -Dmaven.test.skip

      - name: Login to Portainer
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  
      - name: Deploy Portainer Stack
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.PORTAINER_API_TOKEN }}" -H "Content-Type: application/json" -d "@/path/to/docker-compose.yml" http://${{ secrets.PORTAINER_URL }}/api/stacks?type=1
        env:
          PORTAINER_API_TOKEN: ${{ secrets.PORTAINER_API_TOKEN }}
          PORTAINER_URL: ${{ secrets.PORTAINER_URL }}