name: SpringScale Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "self-hosted"
    env:
      IMAGE_NAME: springboot-docker
      IMAGE_TAG: ${{ github.run_number }}


    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: maven
          check-latest: true

      - name: Clean Install with Maven
        run: mvn clean install

      - name: Package with Maven
        run: mvn clean package -Dmaven.test.skip

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}

      - name: Build Docker Image
        run: |
            docker build . --file src/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$GITHUB_RUN_NUMBER --no-cache

      - name: Push Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$GITHUB_RUN_NUMBER
  
      - name: Deploy Portainer Stack
        run: |
          curl -X GET -H "X-API-Key: ${{ secrets.PORTAINER_API_TOKEN }}" "Content-Type: application/json" -d "@/docker-compose.yml" https://${{ secrets.PORTAINER_URL }}:9443/api/stacks -k
